class Config:
    """ Configuration class """
    DEFENDER_OAUTH_RESOURCE: str = "https://api.securitycenter.microsoft.com"
    DEFENDER_API_BASE_URL: str = "https://api.security.microsoft.com"
    PS_SCRIPT_NAME: str = 'ANYRUN-SB-DEFENDER.ps1'
    BASH_SCRIPT_NAME: str = 'ANYRUN-SB-DEFENDER.sh'
    VERSION: str = 'MS_Defender:1.1.1'

    ACTION_TIMEOUT: int = 30
    LIVE_RESPONSE_WAIT_SECONDS: int = 900
    LIVE_RESPONSE_VISIBILITY_WAIT_SECONDS: int = 180
    LIVE_RESPONSE_VISIBILITY_POLL_SECONDS: int = 10
    LIVE_RESPONSE_SUBMIT_RETRIES: int = 5
    JOB_TIME_BUDGET_SECONDS: int = 5400
    HEARTBEAT_SECONDS: int = 60
    STALE_AFTER_SECONDS: int = 900
    VERDICT_POLL_SECONDS: int = 20
    VERDICT_WAIT_MARGIN_SECONDS: int = 600
    ANYRUN_REQUEST_TIMEOUT_SECONDS: int = 60
    ANYRUN_SUBMIT_TIMEOUT_SECONDS: int = 300
    REPORT_TRANSIENT_ERROR_LIMIT: int = 10
    QUEUE_MAX_DEQUEUE_COUNT: int = 3
